services:
  db:
    image: pgvector/pgvector:pg18-trixie
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:ro
      - pgdata:/var/lib/postgresql
    # healthcheck:
    #   test: ["CMD-SHELL", "TODO"]
    #   interval: 5s
    #   retries: 10

  mcp-server:
    build: ./mcp-server
    profiles: ["mcp", "agent"]
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
    develop:
      watch:
        - action: sync
          path: ./mcp-server/src
          target: TODO
  # agent:
  #   build: ./agent
  #   profiles: ["agent"]
  #   depends_on: [mcp-server]
  #   environment:
  #     MCP_URL: mcp-server
  #     OLLAMA_URL: http://host.docker.internal:11434
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./mcp-server/src
  #         target: TODO

  # evals:
  #   build: ./evals
  #   profile: ["evals"]
  #   depends_on: [agent]

volumes:
  pgdata:
