#!/usr/bin/env bash
set -e

echo "Preparing Roles"
psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -v ON_ERROR_STOP=1 <<EOSQL
    CREATE USER $AGENT_DB_USER WITH PASSWORD '$AGENT_DB_PASSWORD';
    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $AGENT_DB_USER;
    GRANT USAGE ON SCHEMA public TO $AGENT_DB_USER;
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO $AGENT_DB_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO $AGENT_DB_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE INSERT ON TABLES FROM $AGENT_DB_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE UPDATE ON TABLES FROM $AGENT_DB_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE DELETE ON TABLES FROM $AGENT_DB_USER;
    ALTER ROLE $AGENT_DB_USER SET default_transaction_read_only = on;
    ALTER ROLE $AGENT_DB_USER SET statement_timeout = '30s';
EOSQL
